services:
  # A Docker web service
  - type: web
    name: spring-api
    env: docker
    repo: https://github.com/yourusername/SpringAPI.git # Replace with your actual repository URL
    region: ohio # Choose the region closest to your users
    plan: free # or choose a paid plan if needed
    branch: main # or your default branch name
    healthCheckPath: /api/v1/employees
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:testdb
      - key: SPRING_DATASOURCE_DRIVERCLASSNAME
        value: org.h2.Driver
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.H2Dialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_H2_CONSOLE_ENABLED
        value: "true"
      - key: SPRING_H2_CONSOLE_PATH
        value: /h2-console